name: Push Event Workflow

on: push 

jobs:
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
      
    - name : Install Packages 
      run : pip install -r requirements.txt
      
    - name : Run tests 
      run : python test_routes_user.py
